apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 15m

  releaseName: ingress-nginx

  targetNamespace: ingress-nginx

  chart:
    spec:
      chart: ingress-nginx
      version: "4.14.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system

  install:
    createNamespace: true

  upgrade:
    cleanupOnFail: true

  valuesFrom:
    - kind: ConfigMap
      name: ingress-nginx-values
      valuesKey: values.yaml
