apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: weave-gitops

  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system

  install:
    createNamespace: true

  upgrade:
    cleanupOnFail: true

  values:
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: gitops.cyrostack.arpa
          paths:
            - path: /
              pathType: Prefix

    adminUser:
      create: true
      username: admin
      passwordHash: "$2y$10$qHkjJ7zeg/smpMGcbXVOh./KGH6kn37g4VfliKwNuDzMNYMWnfwva"
