apiVersion: v1
kind: Secret
metadata:
    name: gophergate-db-credentials
    namespace: gophergate
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:uIqmpAeJyu1f5+Q=,iv:xVcG1AApy/AWMDzShsDaj1thMB+Rj3/R3w9Tv4vcSuQ=,tag:0WAslQ8DjSarwjkrg411xQ==,type:str]
    database_url: ENC[AES256_GCM,data:lxhb0b77eXrcHwLeZBYs73nfYtRfOPCTjWqtvegLgDtsJIDi4h/3/Ub2dlROKstiaS5gjKIOx9hU7QXk08nFKusvOdw5Kx2+zkAHVpdFgM2bcDIy5C1ZNCq/BB3TqQN5k6olGcjypkSbsV1KmQYjmwyJ,iv:ONmoWHTuGKCXFSJrcwhRwJg0G8nxUVxNGJzd5RD0gy4=,tag:trjoygm6HFBQeGzyZ7krFg==,type:str]
sops:
    age:
        - recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMHRNWDBZNWFxOGNCNnYv
            ZEFYUkdXamIweFpNcXdQcFRPTkZZV0NXUkF3CkFPUDNRMFZxbE43b2lpcHFrVW5q
            a1BIcGV1NlBYSkF5QU92Z2RHOTFiUWcKLS0tIHFhWXpxZXdxaG51a25jbld3UW95
            ZFVzbzFDWXVlVGxwRDAvdXpIYk5PalkK0uI2Tc+t2dbJWDHv1UOQDr5bKh1sXztL
            ymvDH+g2o32sRXEExTXWnHm64jLne6WFzzC0dNSVwMapJrts/Gcg9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T14:46:09Z"
    mac: ENC[AES256_GCM,data:QLhdbX9vMXN75fNuzWN/1DDz2/ioyTWL29wT4taBbjB8SIUgYTdJiHmlSkoWZSTAxVsgfwyFFxxhjwMU7PktIeT/h2PM6FOVByTp3XjGVdU5DGhWLUynQ51eRuNccv4GH8749c2xN/fYBTvLjHy+A4+Me1E/u7eG9XSiH0Ajk8c=,iv:ne1d5mwzvs+htZ6yWX6D5ZyTt3zFPMUHC+th8x2TJFc=,tag:9Ibx9qyjRNApgn2hMD8lCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
