apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wakeonlan
  namespace: flux-system
spec:
  interval: 10m

  targetNamespace: wol

  chart:
    spec:
      chart: ./wakeonlan/wol-server
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system

  install:
    createNamespace: true

  upgrade:
    cleanupOnFail: true

  valuesFrom:
    - kind: ConfigMap
      name: wakeonlan-values
      valuesKey: values.yaml
