apiVersion: v1
kind: Secret
metadata:
    name: wakeonlan-secret-values
    namespace: flux-system
    labels:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:FyHM8Nww+GrrDL1X1D5MqKVBS9t9t/pXFmYHChasAxJXFwsK75JcxtXWTw7drX6mNUj7WhtfSKyNCFw2bgqUS/JY3L8duH6KaLvsB2d0vKMBIKknngFwcnESa/3rPHc3nFDsSM1pEIJS31qhXcgOnA==,iv:pAxRZmhaTJkD+rTtqSJ2Fw2R4wdv5r4Z9NoizemnXgE=,tag:hzt5reIWNL43g7CSeNVDZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcStqZ3U3ekVOc3JWejM2
            VGNaWnJZRmlWKytwRUJPRzRiL0VOV21EdTJvClVxQm4rOFFZV3ZPTkJoVGVhT2ZV
            L0tiSzFZRUg3ckNwVndvclFpNDJMVVEKLS0tIHA2TGdac2lvOFZxQ003YUpiUVR3
            NHl0Nlc2Qzl6VCtmS2VCbGUwbXNLNDQKrJjPDwNpCM9R5vwmvohw5WyWiNklqAIu
            sjg4hApB964zyUI0X0CKxGydTUId4SIBN2CSLBTuCeERCTm6UMGA/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T10:55:04Z"
    mac: ENC[AES256_GCM,data:7Y2qHekgXcKYTLT4MfM3eBopuyJn6jEt+t2WbuuFlb66LFolcIs2+chZNsm1BuH2N+bZIYRpz2z7/PmCjyZbDF1SRb49HawPmF6YJo9NSHxhD90DrwxEa5m/NQRxnNb/bcEEFaK4nD6CbxMo/6Wck7satuPfTdMl8SO0gbJZ5N4=,iv:w9j/5+ExFJVtx37cxp0f/Klh/2PtLhH2480BhyHyJEI=,tag:BOSoqC70Mvg0M7bvg8umGg==,type:str]
    version: 3.13.1
