apiVersion: v1
kind: Secret
metadata:
    name: wakeonlan-secret-values
    namespace: flux-system
    labels:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:8PE4NrIXH7dSNjJ+em+HXaWImxvMBkwjmRDmDRbut3pX1eDrb9nV30eKaeli0byuiLa6Mr7GXkI0nH4BCdrkLfmM1Jj+ARCqlaRqmC0mwft/sIluLfeN0FQ6XokTKgdtxefRLlVh4mci6s0hJtpCkA==,iv:0lZn7lvOF+EvmCoWyi/77FTjqd0PMqb0rOfn+bYKN9Q=,tag:vIU1037T/UOT8AhLA729Lw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cG5jZysyQi9LOWhlWjVQ
            aUZkYm85Y0VoczRoWnBvaDE3bXF5ZVcrZ3pvCmNjbi9KaUdvRUJWaWhUTGc0Mkdp
            RzJHYzdqczE3VWFvU3B3VDR5Z0NtMDgKLS0tIHcxSWpqUHJNNFBpZSswQi8ySk1q
            bnAxL1ozakNwWHNjbGloTHNacFlacHcKzm31FYEy3GFhJcP5GiXqkXqjpb7ouHXA
            xOrdRN1fReD83rzK/YEMnA6mR1JKSDXc2rAsQEbZgLQ5SadqekaCLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T18:10:02Z"
    mac: ENC[AES256_GCM,data:znjy/P/qPjYSlIIUkefmRkjd01tLV8ohQBB6MdrWsWGR7oAuhd87jDVmw9UCyClOy7gY0FX1FBH37gMfWyAPlTeAM+nIsqu4HVgqzmUCytOCYcJj869XWdAZPmkYJPjoWPn19t64hivrNBW0tDc2JR+hL66sUEQtX9XDKdEr4cE=,iv:oLJpmrgSdH44H6bAMrm2qv5IBsxzEhEdaCAGuzcIWF0=,tag:CxtQo00r5uV26WJ7cPJUrQ==,type:str]
    version: 3.13.1
