apiVersion: v1
kind: Secret
metadata:
  name: wakeonlan-secret-values
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
  values.yaml: |
    env: 
      broadcast: "192.168.68.255"
      port: 9
      devices: '{"pc":{"mac":"0A-00-27-00-00-10"}}'
    auth:
      token: ""
