apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-cyrostack-vpn
    namespace: cyro-ddns
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:XDWA8oyA/PXJk3GfF3W3R0vbSrW7T3TRULJ/JaY8iK0ixW4Y3pfWq9yARHak2JihCX7eDXk=,iv:3ZcdB0I5UGEW37DNz1FnrG1BNl5fgPnnsYAEgW+KhF0=,tag:ehzzABOuB4HriGaXthDtkw==,type:str]
    CF_ZONE_NAME: ENC[AES256_GCM,data:KLMizTWgWihf+QF5tw==,iv:39FknTcTIljYDwKz12jDs9wU0E6tt7RdATN1ISGyqw0=,tag:/bQw3ZF21yiSBwq7Qf97dA==,type:str]
    CF_RECORD_NAME: ENC[AES256_GCM,data:VT8cFfpYZDIpaSvpoAjBejo=,iv:/QU+gwQ12Ond7u5QrVa+/FfoSzho7iSk4iSng6DzE+U=,tag:yd6zZR1haD4Qq1SRsr+e1w==,type:str]
    CF_RECORD_TYPE: ENC[AES256_GCM,data:Wg==,iv:c6XYFMFpw5GjcsC/I3lvfy/0I5+vNtXiQOYVbi15Lec=,tag:EKtrCO8LlXhWMzrH+mS7Ig==,type:str]
    CF_TTL: ENC[AES256_GCM,data:5X5O,iv:8oEYFYrZ23T75pcxC37Mm/knsPSHEMNb8QuLmKKPCfA=,tag:SsY/5Bt3Fe5m4AUba0GrBg==,type:str]
    CF_PROXIED: ENC[AES256_GCM,data:HzrxoaA=,iv:mXOOrvfPX7+W1YklxrDORV1w2/Pfg8SS1OCCsY47ckg=,tag:z+G57YvUKlxIOMLmrTQWHQ==,type:str]
    IP_URL: ENC[AES256_GCM,data:uQzv4MC+vmNr4kz8BWebsnJ9VnTf,iv:gM4M8mM69ZO7T8U+H9dv754HPsHh0xXYGzO5B4fL+2E=,tag:3MkG1FXoRFJSd/EMsqm6nw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYN3pIaWNYaXlPdEFFcExa
            dXJ4Q3pBb2xkOUFPWEp2YUJYbFVLV0dSamtzCkxqM2dTWHlvQlBvT1IzY1F5WGR2
            dURrN3N1akxielJpWEpEK0xWWXFCVVkKLS0tIDlJNnQzL01qUVplZldNMExYWmVH
            N0JGVEdFaWV5LzVCQjVZaUZ2RmdyNTAKdITU2+Q5M7gAmdsg+oOQmiHxqkhOqJ2J
            2RsXcZExJniMwGG+ENAqBhydurkGZUrMOHW9lc96Q0tbxdvKNBFv7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T14:13:25Z"
    mac: ENC[AES256_GCM,data:26z0aG8rdgYYKDm2ti3JNYkt0h/hfaUjeM/rRokQFgpBYzVy5yfJT0cXfdI3rOLbtR2DdfA4y44f8UrIV1mEJhHIdtLssmpTI9ZyxzBeygKlwL2x54YyqaBZB1hEW7Pzq6QlmkFiIzXIl6T4F2akYtcChWB5+HCZzhBoxecnKCg=,iv:wmVvRJ8zd9GO0XaS2SUy9R5X51COsFjSYImbL7SJNU0=,tag:gW6XJre1vJPgRlgftMYvyA==,type:str]
    version: 3.13.1
