apiVersion: v1
kind: Secret
metadata:
  name: porkbun-cyrostack-vpn
  namespace: cyro-ddns
type: Opaque
stringData:
  PORKBUN_API_KEY: ENC[AES256_GCM,data:DpCfMtGzlBK4KMD0tIczHX0T4AjEoV3OVUNqiOB+60Olh0tqLo7uN6UdyPthT+vOQZVrUo7rERsn2Z7gG58hW+ozYro=,iv:VivZaVrvKMIs1N4ZxjB8RQTYcnmvla2M6F67kOYzjLc=,tag:+aMTrT5jdwGPEHYs6+MgCQ==,type:str]
  PORKBUN_API_SECRET: ENC[AES256_GCM,data:xPhTKDMR6wuiofMfRoiSeaOJSIjOjnya0kYftKYwe5k8rF/16UrYjD5JtdUvjQhRFFQsrJNRrJLXibsYeBbSrvfJ6ns=,iv:C4alSbXBGpdag9IgYjz4nJuXqHaRvcX1DAPN1HlQgiE=,tag:/Lm1UAfaeNzTpCEE8GD/xw==,type:str]
  PORKBUN_DOMAIN: ENC[AES256_GCM,data:yLZ52oSVDtNEJVX2mw==,iv:/NLxHP57e2Ycl2yTbbp10n6l1RPuXTOggrUIQHSXHjY=,tag:tp01W1Xw77N+aPTdZd7Pog==,type:str]
  PORKBUN_TTL: ENC[AES256_GCM,data:POCD,iv:MhLKsiUuxEdmeJiX2Q0wxb7MFJGzmCyAtuT7Ker7PA0=,tag:+RmCZepGHOnAkPIgFmO3cg==,type:str]
  PORKBUN_SUBDOMAIN: ENC[AES256_GCM,data:0Ybj,iv:rYm0UvpUAVLLt9Wm0BhMHoKTXLtbjBGYj3FAvJ/g7aI=,tag:6Dfy3dFaJhjR/rKpSBc4+g==,type:str]
sops:
  age:
    - recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NmhmTzRTYU9KMTNZMDNN
        aENUK1lxak1kaXMzb2Y3RFA4L0xaUUpCcW5NCk1sYndxOVJGZTBvalVWQ1ZwQmFL
        Unk0KzZ1TUFZWVdBaGRSUFl2eWU3a2cKLS0tIENqTU0wQng3ZzNTbVUvdXR4d3hj
        eW4xQVh6UnA0UWlMdDczTzU2RzRTSGsKhWjbFJKJ+m2WscZZcLCg6qSEEraJOznK
        ueJ68M1pwq8fv4KHXiQTWy3Kz4h/WCBOv30vzh840ADhEtR+iE6I2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-09T17:38:08Z"
  mac: ENC[AES256_GCM,data:+3XwMlzL+PnY+Av8bZFKAYeRNTT9axqgeGyIrNlOGuf7Lj5ESD55gh1jBACSuluEyjoZEN2j9BdCHlvozhs7l3rURsz8tLWL68/OlAEfvatDqyJ2GjkXf+hDL0aU8+DgZ6HmvVh94Ogev03mLPbPgTNGFgWIG92xqI0oWqU0XNk=,iv:EmqKW+c9hzAXCoAebNgEy6Sefmtjo/DY8Dpk98lx9kU=,tag:T84P8BMkHtIy5AqRViH6xg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
