apiVersion: v1
kind: Secret
metadata:
    name: porkbun-creds-vault
    namespace: cyro-ddns
type: Opaque
stringData:
    PORKBUN_API_KEY: ENC[AES256_GCM,data:XvYr6NtApNL5+Apkl+MmS7Bu2YwoCTPNEuYiWftAewyleonsLhTny91cQa28en+xzf2h6qUKYFJie2UvUpStW5UQUqs=,iv:VFzNZ5NYysO1TQIBd8xXQjPMUaEUEgOxmbk3+KK8qRY=,tag:b36utJwQqok8H3fGoKGlqg==,type:str]
    PORKBUN_API_SECRET: ENC[AES256_GCM,data:vcbBo6kgcmEer06by6pwKr5P4LfYp7/Ogg6Z4+D/OQ0Q7fCX/U+ejDvYkykI4MMI6a/Kq4uwWuKn1kvh1G5HPCQuCeM=,iv:QXaL6eGFJctI1v7/BFSsFHZpWEYZ1ZufR9yCimOjp/s=,tag:PRWQR2FXH5DjkICV5SpGFg==,type:str]
    PORKBUN_DOMAIN: ENC[AES256_GCM,data:AIp5zsj0qcRyQn4=,iv:u0B/Q8VuqP9cmUbe6EQJt6Z4sy5icUhp+zdvw9tIc0g=,tag:I4D3AtkJ1j/qcloE9vledg==,type:str]
    PORKBUN_TTL: ENC[AES256_GCM,data:j3ii,iv:jTDhXYeDo2PXE11Q2Xy9ZvsxOYvbquO9pxBlV8460Vk=,tag:gjvh3vT283/VRtqB42k28A==,type:str]
    PORKBUN_SUBDOMAIN: ENC[AES256_GCM,data:sVl6fNY=,iv:I/bBrW5/tybrhCXAoc2P3kxwhKwEEAbgdxy7ja97pVc=,tag:jbJD0gOrgUwpMo9teaKk9g==,type:str]
sops:
    age:
        - recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bXZUSG8zcUZvL0g2WTdQ
            djh1aklBYWx4NFRBKzF0NEpUQi9PTUcwclVvCkhTOTMvaWVxYWFuZ1BhdUtjVlRV
            b1RpekJaYmJEcFhKd1R5WUd2QkZScGsKLS0tIElNUEtjbCtVQlowQU5VMEM1ZUpx
            RnFOS1FQYnpENjExYjFNckZXZ2VqSjQKdp4SPeKpZIexqWhWisdNQyPQ9ioQ+N46
            LmazosrY/MBPHlvAhjDONeb15Zg1rRbxXbz/YX9VrwAj/vzTePYP4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T15:25:30Z"
    mac: ENC[AES256_GCM,data:blsIdZ0I33dpf2I7QfeUP23RyBUMsyJNU1QbuLgL3PG5Envq139/tKlroBH8nrgtisjDC0mV+cT3UWvqp5Sr6eh7A1d6jntfOFaL1NuIYlxtgyKgsJyHhNzdNq3zLcw32wuG7z13U8h0IP/DdFTzbAqZSsvyxf21kyk0QsrzyRE=,iv:9bF5ARadBkCyO5qjk9ebSNN8C1uIc804OzsHNviS3tA=,tag:Ub80s/kxcvKF8l8G+2iUNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
