apiVersion: v1
kind: Secret
metadata:
    name: porkbun-creds-vpn
    namespace: cyro-ddns
type: Opaque
stringData:
    PORKBUN_API_KEY: ENC[AES256_GCM,data:+GtL5yr2oC4EEGFu4cl0Rjn3xixTN/D1YdGSAw0CdckPOUMGm9SlzxnR/4qlPrfwFhiDYDDJFda6jy1Yr01FsdVQax8=,iv:lpXaHM2y/ZIZusEnBkunauV7H4c5biMpFbFaBhqdsgI=,tag:s3N0Y0ptMQ7VMtFNmBQZMg==,type:str]
    PORKBUN_API_SECRET: ENC[AES256_GCM,data:gee5RWmysvMgYT3wpS7dVvdMmlyz4jX8Bww26tJELFC1ITdMh2MzCJuU9DYQl+fchXctX7ulXHTHw5s2hE4YpNkKx/o=,iv:4iXe/paPgpndhsgFOw5fCvEib4e698FKLuqJzIlwzJs=,tag:6KJZwDKhnAeJ+gkTWBwbMQ==,type:str]
    PORKBUN_DOMAIN: ENC[AES256_GCM,data:N2L5fvyQfiVzWxQ=,iv:JyqcxImfZSd8+Y6cv7KAFfZGZo6r5W+AXEhH0m1fIBI=,tag:Z0HJkNqGRkwWCkWeIY1Vxw==,type:str]
    PORKBUN_TTL: ENC[AES256_GCM,data:tDJR,iv:xQAuFLE4BHRR258CFt6zw/A+DnqWY6MpjM8hrVVs6MA=,tag:nkk5fg6WnzajbYwaT7fVyg==,type:str]
    PORKBUN_SUBDOMAIN: ENC[AES256_GCM,data:Fl2J,iv:qpNa1eAMLA6dKZwpcnbkR6iG5HyFVO92ONu+77vjZgE=,tag:oiKNFCHV/Wocwe+MFcy1Kg==,type:str]
sops:
    age:
        - recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhc0NZWTBVak45VWNHQjNv
            c3ZxWFZLcjFDYnk5ZVlWQnhFcFRMTnhKYnpRCitNVVFGeHZ2SVUvYlA4TTBjMW4x
            eGVRTmdDZTdWOU5iaFRuTVpNdjhhUGMKLS0tIG9XbnFSUnZLVnI3TG9BRWpxK04z
            T3FWYSs4S1V6RDRvdG1MaUpqRm5LR1UK2pAOWYYMr/DI/IcpiwmJXrDJrJZs1Zk1
            RK2qEyTK9sTHrpYst3zjIBEEN8MG1jnG/f59QsiTWIP1vhTdmjmhZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T15:25:25Z"
    mac: ENC[AES256_GCM,data:5A0eiHUtdimfjwf2REK15po38vxR9BVISAPkr84b2Q2IjIwzRQvz/x59YEpRlEbbbuvE+qrk9Z1lMFgzzjPvctPj3CtQdc429rfD8v0P3KFBTr9TL/QntqHJOZpcMElmx/BQ5SulDXw/0GiCuE4FjhJ+D/N5RJQnPaPVw9Pe3e4=,iv:u/kKtnzVOXcFOLWPJVGf0ASZ7e2CWZf03QhyX+dIyTk=,tag:asmODYeWsa68IdGF2wuYPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
