apiVersion: apps/v1
kind: Deployment
metadata:
    name: gophergate-ui
    labels:
        app: gophergate-ui
spec:
    replicas: {{ .Values.ui.replicaCount }}
    selector:
        matchLabels:
            app: gophergate-ui
    template:
        metadata:
            labels:
                app: gophergate-ui
        spec:
            containers:
                - name: gophergate-ui
                  image: '{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}'
                  imagePullPolicy: '{{ .Values.ui.image.pullPolicy}}'
                  resources:
                      requests:
                          cpu: '{{ .Values.ui.resources.requests.cpu }}'
                          memory: '{{ .Values.ui.resources.requests.memory }}'
                      limits:
                          cpu: '{{ .Values.ui.resources.limits.cpu }}'
                          memory: '{{ .Values.ui.resources.limits.memory }}'
                  env:
                      - name: HTTP_ADDR
                        value: '{{ .Values.ui.env.HTTP_ADDR }}'
                      - name: GRPC_ADDR
                        value: '{{ .Values.ui.env.GRPC_ADDR }}'
                      - name: GRPC_TLS_ENABLE
                        value: '{{ .Values.ui.env.GRPC_TLS_ENABLE }}'
                      - name: WG_IFACE
                        value: '{{ .Values.ui.env.WG_IFACE }}'
                  ports:
                      - containerPort: 3000
                        name: http
