apiVersion: v1
kind: Secret
metadata:
  name: tunnel-token
  namespace: cloudflare
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:ED0P+Vb6+I3i9OyVQSV/Srtp/aWgvRPA1ICNyIfYh+qGhW2eypYflC5ysghkID4W/nkFNjGGOUAxd/RI04ZTDFwwGdNj0SLuK1n7AYHxQXXmZ+M0tWnm98Jlk5Zy6T9+FY51MxAAwIsBb5s4BEoQoPyL8rIhOeWy9KJV4MROIGEkxKKZiA8x//9/fDcQjd0kBhH0nUbWJdH3ctjkm02J9ES9MUOf1UlwSeIlN9li4NGCjC6eVNTaxg==,iv:sQh4i1TsCZijdj+MCcgdPab3AUFyuJKUO8a8rFGFcGk=,tag:NS+caL1e2XeK6KqBH/RE7g==,type:str]
sops:
  age:
    - recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodzY5S2NWc1E5ZnBKZEtl
        MXlYNFpwZFZRckNwKzNtYnJoWkY4UnlKd20wCmFJanp5UlpaRThBdlg5THAxZUI5
        bmtTS3ZiVlRxVFJrYzlXT1lPUXVMMW8KLS0tIE84cXpwdGlDeDkxbVNKTkdLQ0Vj
        cG4zOExQTlJLUllqejFWRDNheDlzZG8Kbju3xnlJ7iaPURqirmkhqA+2zi389DlH
        3qy7AGir3X+UnMx2HyA4mSF+Q/9ZmyQCtT0/8IprvFAkswMsrL1k1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-01T11:19:59Z"
  mac: ENC[AES256_GCM,data:OkQl14EgmOhBa4PNHBJR2qMHA8RUESS0VdPeJCQWx3+Zxbr3faWfXTfXB9PJTjXWYmry8nB85qCw2fK8NZT+SdkAuzFodNuOV0YI8YkGzz3itpnAkVtSvU0r19oJYPvivpgigGyj5N3Z7lhqj+VMHbyoNhzwYL48Kv5u7xRztmI=,iv:VzymKY5gvKLn+NePm68eGtIoGdLrauMFcI0f4j4sK1s=,tag:q1dWjDukERuJBvkNnAWFSQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
