apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
    namespace: cloudflare
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:OvtRH3l/D5HRKtEVYfyjadIOv2p3ui1Ez1AkFiVnQn4wF8H3jiwqmWA3hDJL32kTdXA+sz9kstByIhWaWdPk7UwZ2EPku+TtATR2XQmUy43aAlVsboRvseecmhNPQVuqzLwtBUc/oLxHG+tOKjYu2IWltVvXpby52+ddaROPn0NN0nfOFZOJCm1lrMvUdQYdBhoYvcXkvfl67PKbfvmnbzby+n2ixwU4kArOD45Duac5qWYMeYCciA==,iv:ml7bMEt4Q6UxJfxwKSea3eAiYZwxuOuXIrzm2fI54Bc=,tag:P2krgTNKlOgDwsMM34I0yA==,type:str]
sops:
    age:
        - recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RWs0R2c1bXZSSGM1Z2Iw
            ZVNQejdYYVRKcDlUUUdhWTduQTdKRnkzd2lzCjUwRTBtUFNjUDB3blhPdnJXRENs
            MzF3eEx6Zy9vYk9JTmtEM1RXdmdVRGcKLS0tIEFMb1dGWXlHRUhPTDlRT3hBc09K
            UHNydzB2ZHQ0VEJoamNnb2gvTXpLRTQKxb+pQaR5kMxGZSVRfDmWqRUhgI4XpFRD
            3i3M56iBGbsT8Xrc+KFtRMYDya/ZYFkNv3miPdTELGK84GKkYmCYtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T12:23:25Z"
    mac: ENC[AES256_GCM,data:mDRn0z/WvN9OXelbzOVQbvFBni65VBrer9k6kX+HtGZZeR16WVceLibR7Q5WVbgVic1Ow3Sebf0UipYSbvM8aB9k2RiiqG1WTihxaj7IS6VX7L/HlKc/EFTK5HL4nhNz1wdWrnfKJ+G6ntX6OKp78X8j2/knhVl7V4haJ3iOpnY=,iv:EfOFd87T5Phzs4DNzY6wq5PPIEB2AAlcBFIyJQQoZNE=,tag:vYM6v600OEFNkGsPnDqDHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
