apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
    namespace: cloudflare
type: Opaque
stringData:
    tunnel_token: ENC[AES256_GCM,data:2y2kF2R9iZevV5lXYdAjsQ4FFgwLQsRp34A86YBhaLg2jmvvSFT3tFDH8jP5t57/0jWLPCLph8ZzwrckQW1G/cjy8t56exyTzWfbIkT1Z4n0IZ+xYcJKOniBmN0/po0NEHcinHGdKGzG7FFVNR2BxB3JmDkoww2BwM3LBN/VC2qKnfT2pssLnorc+qR6kAP8FemxjQbuNYy8o3MkmQtWEBirnGe7Sv0oKoCWozWFm418/SqvjL5+QA==,iv:Ks418ztHSJ+O/3RUUUFpe+GljlAv8vpCGfogYUCAtiI=,tag:fcalSn+vN5xN3yzqlIBi6g==,type:str]
sops:
    age:
        - recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubG1PaXJ2a25RQWhxeExq
            cWRlZUlVbktINlA1d2UvTEVub09sWUZhUG1RCkhoTTF6SDYyZGNzeEZDNldNcUFk
            TEt2Tm1rLy93UnRLbThVQ20rTnliYTQKLS0tIEIwajI3S1p3TzE3ZlFUbGtpdDJJ
            UUtKUFR1YitmQkVGb3lJZTIyQjV2REUKOSwTEy5v9emoX6oe1oMuUb4a0vbxYlIU
            p3ygKYVfmEeoyYQlSUC6gTGmIjssVIIDgs9GTQW4G3Og2QvgR4RLDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T12:25:19Z"
    mac: ENC[AES256_GCM,data:WYH0x516gGphZkYF0oTavDtn/Fi8ryBdfmk9ELNUjksMCAjHySKLRVvTdjPr4TJXScor29DsLuUvu5TbpPwKrze82nUFKd0r8YTCtd6kt7c6zSGUstLIvTBoq9MZO/1w/FkRdGBKFngESTbhB64OgVs0vUT8PtnlwhPSQ8aFsy4=,iv:KA4T7lIXrqFLi1cmIZh4YPWpDlljJ+5yosi4yj2dlZI=,tag:ToC2ktSuLhkRMmqCGmtkOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
