namespace:
  create: false
  name: cyro-ddns

image:
  repository: ghcr.io/cyrof/ddns-updater
  tag: v0.1.1
  pullPolicy: IfNotPresent

cronjob:
  timeZone: "Asia/Singapore"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 60
  activeDeadlineSeconds: 60
  backoffLimit: 1
  restartPolicy: "Never"
  suspend: false

jobs:
  - name: vpn-frequent
    schedule: "*/10 * * * *"
    secretName: cloudflare-cyrostack-vpn
    successfulJobHistoryLimit: 1
    failedJobsHistoryLimit: 1
    ttlSecondsAfterFinished: 300
