apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 30m
  chart:
    spec:
      chart: vaultwarden
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
      interval: 1h
  values:
    image:
      tag: 1.35.3
    env:
      - name: TZ
        value: Asia/Singapore
      - name: DOMAIN
        value: "https://vault.knfolio.dev"
      - name: SIGNUPS_ALLOWED
        value: "false"
      - name: INVITATIONS_ALLOWED
        value: "true"
      - name: WEBSOCKET_ENABLED
        value: "true"
      - name: SMTP_HOST
        value: "smtp.gmail.com"
      - name: SMTP_FROM
        value: "hs.auto.noreply@gmail.com"
      - name: SMTP_PORT
        value: "587"
      - name: SMTP_SECURITY
        value: "starttls"
      - name: SMTP_USERNAME
        value: "hs.auto.noreply@gmail.com"
      - name: SMTP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secret
            key: SMTP_PASSWORD

    secret:
      create: false
      existingSecret: vaultwarden-secret

    persistentVolumeClaim:
      create: true
      size: 1Gi
      storageClassName: ""
      mountPath: /data

    service:
      type: ClusterIP

    controller:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9108"
        prometheus.io/path: "/metrics"
      updateStrategy:
        type: Recreate

    extraVolumes:
      - name: exporter-script
        configMap:
          name: vaultwarden-size-exporter

    extraContainers:
      vaultwarden-size-exporter:
        image: python:3.12-alpine
        command:
          - python
          - /exporter/exporter.py
        ports:
          - name: metrics
            containerPort: 9108
        volumeMounts:
          - name: exporter-script
            mountPath: /exporter
          - name: vaultwarden-storage
            mountPath: /data
            readOnly: true
