apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 30m
  chart:
    spec:
      chart: vaultwarden
      version: ">=0.0.0"
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
      interval: 1h
  values:
    env:
      - name: TZ
        value: Asia/Singapore

      - name: DOMAIN
        value: "https://vault.knfolio.dev"

      - name: SIGNUPS_ALLOWED
        value: "false"

      - name: INVITATIONS_ALLOWED
        value: "true"

      - name: WEBSOCKET_ENABLED
        value: "true"

      # SMTP Setting
      - name: SMTP_HOST
        value: "smtp.gmail.com"

      - name: SMTP_FROM
        value: "hs.auto.noreply@gmail.com"

      - name: SMTP_PORT
        value: "587"

      - name: SMTP_SECURITY
        value: "starttls"

      - name: SMTP_USERNAME
        value: "hs.auto.noreply@gmail.com"

      - name: SMTP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secret
            key: SMTP_PASSWORD

    secret:
      create: false
      existingSecret: vaultwarden-secret

    persistentVolumeClaim:
      create: true
      size: 1Gi
      storageClassName: ""
      mountPath: /data

    service:
      type: ClusterIP

    deploymentStrategy:
      type: Recreate

    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9108"
      prometheus.io/path: "/metrics"

    extraVolumes:
      - name: exporter-script
        configMap:
          name: vaultwarden-size-exporter

      - name: vaultwarden-data-readonly
        persistentVolumeClaim:
          claimName: vaultwarden-storage

    extraContainers:
      - name: vaultwarden-size-exporter
        image: python:3.12-alpine
        command:
          - python
          - /exporter/exporter.py
        ports:
          - containerPort: 9108
            name: metrics
        volumeMounts:
          - name: exporter-script
            mountPath: /exporter
          - name: vaultwarden-data-readonly
            mountPath: /data
            readOnly: true
