apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: vaultwarden
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:64V7trEO6FYdGk5lyafVWvWlIJWYq5A/8H7PyP9R/BGAmr9sC31w+A+TcYho2jX7sX+c+stJx3ekvbmGqkQjKw==,iv:teTZ67oNX1Sri8jWpHTgvqZ2ZJrNONYIoqwD8Q8uT34=,tag:wbV8nvDSiu2eIBiIzTAbLA==,type:str]
sops:
    age:
        - recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcVpmMUFpZ1I1WlRwOW81
            aDAvbjBPSE5BU2JZN2s3a3JGL0xBSksxam4wCmgyMFpyUXN4dnM3K29pQVlHVDRm
            MXdQRFFWNFR5SFZDNXdBdUtDNmtjcEkKLS0tIExXZkNobWgzc2ZLaFV1S2JTZ3RJ
            a2hrd2J2U2c0bUtlcmJRSjFvUDhoWkUKp11dUSiK53sYyo8H+VK0GOoA5SncM2XJ
            6/Bh6EDAYzdLm9PkZDrINmdADhgVH8kzn8FDbneQlDyZD32IhRZVJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T13:48:31Z"
    mac: ENC[AES256_GCM,data:oz7aJBbRqHW0PuNkNph+6sDWwMKEih9o/bZfpQJSjWmn/AibrOlTwGbySShblK1tJLBK3z5Y2wqrENjJ7MMxSet9JcIizJD3LLOxbtVTOc6SWWuh/sX1coUZRCRL+FfhohwQoCHFfa52SCsGO0113Euq3YbpzbXfR0AKmLtgJRc=,iv:2XtDJnRqoqdjKwsZEFlM4fKL1vFjqdPBFJdRAK41We0=,tag:nHVMvf5+qqPTFPnm2j18xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
