apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
type: Opaque
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:ENQ1xenyrR+GAN7Nn5hY6CY24g8UjgPEhc3w+iGpEEIERgzpBEE2W/N+rM38OMMCQXYNw2Xc1RwE4rjCQGdEIQ==,iv:HEV01hyTMjNW3xIsySa8N3slbdbzU3YRYbhyAwQWTbc=,tag:1cB5pchW28xE65rl6E3Qtg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:2w45wuZOdravsJEejZ/9Ow==,iv:cAzkR3H7j3Ea1b/tBum4OC2pICcEVuBphCctmMIfQ38=,tag:JKPmm5GPdTsSyDyA8KDzjQ==,type:str]
sops:
  age:
    - recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RGtiNkpuWHpkRGRrL3RE
        S0JMT2xjRUJPQUM5TithU1RYS0xYNEhpNWlBCmZiUnZsMWVGTTJ6WVhGc0g5cm16
        SU1jK2wrbXlrL25Na1poTEJoTk4xdWMKLS0tIFFWTzBWSUFSUGJqUjVLa1dzYTJi
        dFBCcHdNWVJMNWxQQ1htdU1TVkZyeVkKtpomPvBOV9QkqW9awekVLuHtTya1WZ2z
        1SQHo61AlCNjYDcmkHP+1hlex35kHXLPK8OyHUjOfbO4g+cc6azJjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-25T14:53:56Z"
  mac: ENC[AES256_GCM,data:ZX2u/oLcmHPNNoAAMy20wYbdbS0SGGv03N7QI/eAXMuLwcnZbp0zBoxjr/J0c3Ihnc/861ePOcYidLth4RFCHpWQ/8QfGXxoHSbwKBRlVKz76VYeyblNWjbXscr4iKcXLYo5cj1HXEDduSzISoslNQ/Nb4ad3YOshGPk+4OQ4R4=,iv:ZFwyi5WCBRGwGc1MzWs3dDehhquUOupS9vrSgyOA9iM=,tag:b+dVUq9KKIgJ2AiZvnNsGA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
