apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage-nfs
  namespace: monitoring
spec:
  accessMode:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 5Gi
