apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:tYcAufg=,iv:+JSnujDkfL5JoFcbOA3EtAAEyWyop5ide7XaxvCDD4w=,tag:xBeCHcHCRUbNfKShpz+jsg==,type:str]
    admin-password: ENC[AES256_GCM,data:6ZOcQnmFf8P/Z/X0Oas=,iv:84C7zdo3wMekxFzfdKu09NLctKJzd+Xy7tYm3EvcOzg=,tag:ZbEMim/CzngRSd4ia1jQVg==,type:str]
sops:
    age:
        - recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWTFyMWtSU1V5clZDN3ZE
            c3RtOVJ5QkJ4VWgySGllMXV2ckREVk1oSndRCmpTN2dMSDRTb3ZiTWRkYmdoVWVo
            akV1R1RzSDJjZHZoN1dkem5HdkxvbzAKLS0tIHg3cEhGSlBsejVOYmlPeEtxcjR5
            aVFFYnJueFpaU3ovZ0QyK29PMXhkK1kKEVVxI9XM8BYsREwlWYEG3VMSqzf0paJv
            6BzWiQ0K0/dgqORiMpjbmAq12bm6/54r1EqBN+e2mwLS0cGM9hggHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T17:11:54Z"
    mac: ENC[AES256_GCM,data:YT6QW3Rf3vkOJ9Sy6H2Kcga+hpU1byPLrWTWhhOQMwJlRNYRrXUtAH9PNvgNg3M6wkuHTGoM6QeCTkj9fLSEnjOhODMJR5Vrn8GLVZlJbPfE/mLyvIZrEnH/Q0SngtkwzSqwtYzzUCN6axvarF+lAcG//hp25WiQWEN9s8xiB2s=,iv:TuW0bNoMzPkvVp5ZkeJ+Omw2SvdaU+MOreg1VsksOS8=,tag:voJOeVJCwiU48kBnDB6siQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
