apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cyrostack-coder
  namespace: coder
spec:
  interval: 30m
  releaseName: CyroStack-coder
  targetNamespace: CyroStack-coder

  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1h

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: coder-values
      valuesKey: values.yaml
