apiVersion: v1
kind: Secret
metadata:
    name: coder-postgresql-secret
    namespace: coder
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:Dt1AlvtgmtNG5as8frRAZHQ=,iv:fcp6PKbwV+fTxjBahpICs2tnJVWBd2f50atMY71Bwg0=,tag:cR/PEVwRzZejbQEpXyvjbg==,type:str]
    password: ENC[AES256_GCM,data:pcRzO8/7OMYrM42U/WovQcg=,iv:zPHHLXzwUq13hkuISOUIMMen90dwCUw5PJpKtmWtL2c=,tag:gzQyZTl+q6eFlzTZ9ennGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY3hIenpNcXdTbGxvL3JM
            cmdQVkE5MFJZVm5pLzhSdlJaNExJVE9lelZvCjQvMWVvRkxxOG1yWHh1d0htZ1RI
            TmJRS1lYMHA4ZFZBQ3FFcGlyN3pqZmMKLS0tIGJWSjhRRDExWHZQNmlmSnhCTUdK
            bmxzR3Q5YXZIYW1WODROL3lESXhhVlEKkfdBxLFfwuO83xBmiS/mn4euij1EauIT
            LwwR+K4JXbOlPFvS+URMfMik8C7y26AMh++Mxkzu7K4iOguNyV1LPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T05:37:34Z"
    mac: ENC[AES256_GCM,data:FH0vYnvtyZzN+OVyjDgcT3Z85MjFu88e48me3ciDgZ0cbOK4RfMzLZNdPqIbdy+CiXp8Plc23lU87Xm7hYpSWnFEPTs+ysK3z/mvgutDNCaHBbb5tPKQ7FITjFzWDWxQDDT2b4kZL0NzLuAXo81lhL6rRA4SzlKFRmTIeYCeSY8=,iv:sDM9+Dx8cQchErR7dsoCDONbGGtNc5CofqXbFfcAYo0=,tag:5Y+9vrHme5QlQXLR7LK0dw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: coder-db-url
    namespace: coder
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:hfiNODQzBeAMDotK2j0hhFpN4PXUjPZZQsODA1Q52F/89MQyPSrR/D8p0TUvsnPbnUDChn+yJaU4JI8kOHejINovOKsvHwsFvPGeV6WFYvJEhZ0yQY13xdAs9zc0vweDW6CqsAkS,iv:uxA5H7fLPaXl4ZB10m5PpeI+4Lv+hviErYqQQJDZBWA=,tag:jnGb3tTypIyQJPgXpFKSrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY3hIenpNcXdTbGxvL3JM
            cmdQVkE5MFJZVm5pLzhSdlJaNExJVE9lelZvCjQvMWVvRkxxOG1yWHh1d0htZ1RI
            TmJRS1lYMHA4ZFZBQ3FFcGlyN3pqZmMKLS0tIGJWSjhRRDExWHZQNmlmSnhCTUdK
            bmxzR3Q5YXZIYW1WODROL3lESXhhVlEKkfdBxLFfwuO83xBmiS/mn4euij1EauIT
            LwwR+K4JXbOlPFvS+URMfMik8C7y26AMh++Mxkzu7K4iOguNyV1LPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T05:37:34Z"
    mac: ENC[AES256_GCM,data:FH0vYnvtyZzN+OVyjDgcT3Z85MjFu88e48me3ciDgZ0cbOK4RfMzLZNdPqIbdy+CiXp8Plc23lU87Xm7hYpSWnFEPTs+ysK3z/mvgutDNCaHBbb5tPKQ7FITjFzWDWxQDDT2b4kZL0NzLuAXo81lhL6rRA4SzlKFRmTIeYCeSY8=,iv:sDM9+Dx8cQchErR7dsoCDONbGGtNc5CofqXbFfcAYo0=,tag:5Y+9vrHme5QlQXLR7LK0dw==,type:str]
    version: 3.13.1
