namespace:
  create: false
  name: cyro-ddns

image:
  repository: ghcr.io/cyrof/ddns-updater
  tag: v0.1.0
  pullPolicy: IfNotPresent

cronjob:
  timeZone: "Asia/Singapore"

  # Guardrail
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 60
  activeDeadlineSeconds: 60
  backoffLimit: 1
  restartPolicy: "Never"
  suspend: false

# Define jobs
jobs:
  - name: vpn
    schedule: "*/10 * * * *"
    secretName: cloudflare-ddns-env
    successfulJobsHistoryLimit: 3
    failedJobsHistoryLimit: 3
    ttlSecondsAfterFinished: 300
