apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: knfolio
  namespace: folio
spec:
  interval: 10m
  releaseName: knfolio

  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  chart:
    spec:
      chart: ./portfolio/knfolio-chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m

  valuesFrom:
    - kind: ConfigMap
      name: knfolio-values
      valuesKey: values.yaml
