apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:oAY67BMJhyTbA7D8dbTvwBZIZ865pAiMkNOzYZRw1L+9EgcPDDz5m/bThnG+vjCc32PSEl0=,iv:MOAZZB4fzhUUo4jKQQgRdDclgK/DCsPCnqCNA3M9pwk=,tag:1ndVq15IvIqFJqibvjvNDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0K3ZoY1pGZCtlYjREZWtp
            bnVSWU5MMzArY1ZFL1dwdTcxTHJFYzZPTzJNCllseXJSam4wUUdOdkwza295RVVF
            bHIxeDFONkhKQnRrWlNWelZZTCs4clkKLS0tIHZadlVKdC95Z0lEanE4cmhCdnhL
            Nmh6bm1KMFl2dkxSQUpTak9zNGc4NXMKvMLdXZn+8cjh5lZ531L5xw0SUaiVfCqE
            kNV1VJoHf6HpxEFJR8sPA8hl7drUPLv69Co1YV389eVBP1WE1lSk6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T08:17:22Z"
    mac: ENC[AES256_GCM,data:DLOysvRUbUZ60BIivNJ4ICiia5XKObTiYa0roRTZG1s3eLpLsolW9EcntPVkz63bl4uhu99Zn3y83F2OhnVZ14VSrz6SjXgDrgkKVpo+KsEsfi6GUUEIeE4yuHI/EkoQ2jchOkm5D/3RRbhiiiHxaFcXbXRh99OpVZDtRd67kRo=,iv:liGDSAquGBxmYJsW+Q9vcPLs/ZVkWkynju4CxLZAvfA=,tag:arZglHNlFKjmrxdKlyGgLQ==,type:str]
    version: 3.13.1
