apiVersion: v1
kind: Secret
metadata:
    name: porkbun-cyrostack-ournezt
    namespace: cyro-ddns
type: Opaque
stringData:
    PORKBUN_API_KEY: ENC[AES256_GCM,data:XG8VC8XkIVrIBlwYeZUVIquXhVXXxOr6OdbtTvRKNKbMq6k6gYR5wVlPlOuH5ekdqmtH1qoCjyRGZ7X5+Q/jG5HoSyM=,iv:M2SH/vcu+6OSij2MBal99omgd66kD+bPBUBPj0P7BbA=,tag:0ZHAoQnd/5jMtvS/81Iivg==,type:str]
    PORKBUN_API_SECRET: ENC[AES256_GCM,data:wiVs/QtE03euWcoUVi8ltq1WqW1gCQ8eprx5HO66OAwirqAuK8XaQxmjXh4ZKxkXchvguILIf4VGh3XvOeyqxqsHs+0=,iv:0YR9Fe+wzZ/qn1Cw3Yv1/8ZhIx/snIlrhpSzpIYi9jA=,tag:VO2gEPLYsu09AvlsoG/jrg==,type:str]
    PORKBUN_DOMAIN: ENC[AES256_GCM,data:HBkIq/mEAqPOh0S37Q==,iv:u6hoUUpufG8ZD/0pS0t0jE/1PxHg3Ezp7L1+QAJS5CU=,tag:bOCTIM+fGFckcw0nBIX7XQ==,type:str]
    PORKBUN_TTL: ENC[AES256_GCM,data:rXOx,iv:gE0LdWWWZxa/+xs3uA2Ll5U4NfFtDQann6oEl0dabMM=,tag:/+AMq10ZQANtajLwxlTO0Q==,type:str]
    PORKBUN_SUBDOMAIN: ENC[AES256_GCM,data:8ZG9w70OVA==,iv:p3/vXNTYI8ayfCe5cwdLvYCZVF/BepjZM9ur43Ssxok=,tag:FC//rGSvjnWJm4OHUlM6Hg==,type:str]
sops:
    age:
        - recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXV1RRdkdpTWo3QWhmbDRu
            K0ZSUWoyQTlnSFBJKzhDUmxsN3hYYzNpa1g4CmYvcW94eHdkczFYRFlvSlFCOEtP
            TkN3VDErRWVmZFJiL2Z6Um1iT1dhV0EKLS0tIFB0SmxESzJDZlFsOHpkeTFKTUw5
            N056NUxRRGxxSGhXU0lmUTRabkFYUkUKqI6BNrGcrmGBlnvvBYQ3Nq8mKK4M+9fg
            9YQLz0suEAxRVR5CgXytA0/7grtfyC/sYvPbHiMSKzvIKUqHPiNdpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T08:00:28Z"
    mac: ENC[AES256_GCM,data:iXwmXPoqzC6qtDbPmGVYrzJzNMWwv56UVEjW/46jsn/QjFo0JvM0a8GVB0DXTlnoXOjDTvLje/vNn63YI5n1fd8Y/2/YQ5Tom0fR2ydWFa7gOb3elyTcdAcUSNg9pkVo3MD3WU9Eh4gNyhv2T3ZmYMEzgKZCuCMElhne/l+IIMo=,iv:fNP3uzyx6TGgLVQ+birGpNuGV8ZXT+MFpMLL92lbSCQ=,tag:Ivhjw2ZE654Uu5vM0/DUBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
