apiVersion: v1
kind: Secret
metadata:
    name: porkbun-cyrostack-vault
    namespace: cyro-ddns
type: Opaque
stringData:
    PORKBUN_API_KEY: ENC[AES256_GCM,data:K9QUtfd3p/uh5TaMkczUw7rY5zVLMAwh+y9Erjr51cvVmbTk73DJGIM7K4Q0PEO4Eud6dStOSQzUlfZ5pXixMI/ECZ0=,iv:VYpsGIIwse1OM5tDqw3L4qCTB3DvmiKHG8tFuWAZvnQ=,tag:3RJbNsCE9rLmBdTvbStA6A==,type:str]
    PORKBUN_API_SECRET: ENC[AES256_GCM,data:2/s8k4myaZsiLvOD4ohaShqbuufGsuzQ2DnqSYLnx8RNKVWpWlLxHy4uz0OH/kTebjYDk6u8eBIPTkpYYx6NhMRGzqU=,iv:Fllraf6KpfPAkdNQVvUkXK7XW60dTh/MaH3xVr4hesM=,tag:4jpQGzA7Gd9yttMaPyk4hg==,type:str]
    PORKBUN_DOMAIN: ENC[AES256_GCM,data:oTI1gWSxpXIQAkuCAQ==,iv:kAITvzkWzVFuUnDMv9izeN751biI9p5gOMWh8ddY8qY=,tag:9hSPpgzt5xiVHDr9sLj98g==,type:str]
    PORKBUN_TTL: ENC[AES256_GCM,data:fN1n,iv:HXeT4DGJ9e96fm0eev5WbWjP0L2U7hThPulIt+0q9mw=,tag:bkHc7fqRvG0IhtCFLSmPSg==,type:str]
    PORKBUN_SUBDOMAIN: ENC[AES256_GCM,data:m2mb/T8=,iv:zDNfFIXlsd9DGBwhz/HAVTRJ0MoBiBkc+TzfdE9wj2M=,tag:/SK52roi7FQbhdtqETztpg==,type:str]
sops:
    age:
        - recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOVpMZ3hQWEFBTzk4cDRE
            UzhaR015eVp5c1ZIczFCYmRGaGRVZGdUSmxVClc5V1hpb1lkOU9DN1F0Q0U3SStS
            amc3RG0rVFJqRmlXUUMwM3p4TFdwV0EKLS0tIDlSUmpHU0dWZVNoRTNxQ2NJR3g2
            dVNZMG9XVFpsRVZ4Vlo0ZXJvdG5pV1UKdHA4GS4sPziK/BxP9HTT6A/D8CuHUYEa
            BLXSSiHhXn1K6+oNQxf5kF2LoHsVM1hR0nKtE1BPwRT/LsZshoZsSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T17:37:59Z"
    mac: ENC[AES256_GCM,data:ZeW+oDDvxmJfwKKEQn/ivZ8DtRQ9U5erYPGQTkm2zhUSJxtmGjzmygdS1WoLAnSZm7QJYZjv46kHKIoVKTkjhey2W8lPwyTNs4NAiPK/nuvbh+sH4FnmiWWE0IqV6ga4sFaGga2m+jMlFh6tF5Dlvg1xaiBlNnHP0F9Jo+IqerA=,iv:o7cMdNQlHOdbJa4BIOmsdWsnqqN7UwqZ4k5Vhg4E9Ys=,tag:sWFa+qMda1wWve+RixPfQg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
