apiVersion: v1
kind: Secret
metadata:
    name: porkbun-cyrostack-portfolio
    namespace: cyro-ddns
type: Opaque
stringData:
    PORKBUN_API_KEY: ENC[AES256_GCM,data:rKXOfffrQpk30A7wCeLhpcgzp4xasP0r5VrXVcde2gKB1zvbsBdlB1y29lctW9mmVVxz9r1LrMzFKIPOeiVtSvrCuiM=,iv:Sh73MrpPWKi9JNVycRjK6i076jHxCrT6ATD3F8fxHb4=,tag:c9UevRec1NHuIXCPvw0n1Q==,type:str]
    PORKBUN_API_SECRET: ENC[AES256_GCM,data:nV/gDXl87KotabqO4OhnM//W+d6VO+GYtfYa/1oHCQyy0BVYGSK8wWPXAVScgzyU4DPsQ3Ka+/BZ/zZ7IMKt+Em/W5E=,iv:wPMoHpfGxr1cQNqCgrDg//3xxT8T1htczJ2SfNK8c0w=,tag:q2nE91Gvsk4cgHbrTLJj3w==,type:str]
    PORKBUN_DOMAIN: ENC[AES256_GCM,data:smZ47Xckp71jaLhyEQ==,iv:a1khtfv5VwBXG4OBqTRZR602tg/pghL16Cnfrd7AR5U=,tag:/Vu5LthGQ3Z5GeNuwadt5w==,type:str]
    PORKBUN_TTL: ENC[AES256_GCM,data:Q+06,iv:SOha14QnsPRYuMLe5Dg0m7feQUMWPq5NGE+a1OdnQPc=,tag:eupvI0XO6AT+gRJVtprfmA==,type:str]
    PORKBUN_SUBDOMAIN: ENC[AES256_GCM,data:GJWe/Umd3Q==,iv:h6ZB+Xxyaqd6FJ50IjiqZVSRipxeFMsYoCTJ1GgoDpk=,tag:z3NF4vmzOPqoZsBPLrv47Q==,type:str]
sops:
    age:
        - recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQy9tVFhzbER0THhNZEtl
            SzdsWHVrRk1lWVVBTWtxcnBFTnRiR0xjQlRjClVxQjhuUGd1N20xN1MzUVZlanA5
            SjNpQUFIM2FneGxWbDd4RkpLRzVCRkEKLS0tIGdyakwzcEtpNVFDNDNKbmQrZTd3
            MUFWL0hvUUQ5TXRFaFdiK3laMkh5TTgKfRHxTD4+gQXWe0AnEr9NqQgNQg6Y+LZV
            3OmebvfiR2GmeI8eY0f2s2nYA1QVkiCLjSH5fO9jpj5efOO7vjjUGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T17:37:38Z"
    mac: ENC[AES256_GCM,data:ZNiLW/moh+8Sm2oETNEF1d6wpt9Za/yA1rYL96EVjtOqnh0bVRKv2E+d4OkUo9E+sctqeoAgeIX9SMCuaXZxebQe6SBjQXl1YrxuES+UragIja4qEYwWyfeP/veJp+8tB6ypL2gEPTpQBQrrBpDoNIBBrHK8ckgy4BcX28GSaKE=,iv:qEl1h286cDmzd3rmCzEwZhgpvQi2VCblCgGmQ089704=,tag:EFrEpm/Mz0/pRbJ4FZiMcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
