apiVersion: v1
kind: Secret
metadata:
    name: ournezt-db-credentials
    namespace: ournezt
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:PZ6CDKcxYVvtCzvA9YM=,iv:59CWP4qhxiv7J57rKEVOrPv1E05Mj5lQULCJysEv/w4=,tag:ZM/0AobjBG/ILKxR2t4kIw==,type:str]
sops:
    age:
        - recipient: age18nkk5pllyvdac3rn9sm7u925vzke2r3gt6yflz6gt7vmscs4jarqv9l76w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNnlGcXk1ZFVmMldkeHU1
            ZTNXUFcwMmVZS0RFOEN3VmpPc01KMHVQdTI0ClVZdFBVWDBTTG9Lb0w5M2ZpbFBL
            VUtTZEpQS3FkQ3hEVlRxZ3FTaTRBZUEKLS0tIDF3TVpDZDdCZFdaTUhCWTlRUW1E
            alA4SnVSK1VVR2pkZ0gxdkpHSmwzVzQKfZJPhBEUhA+L0zai4IEPRXUMd7sDOlta
            WGfrmj3RuGdrtbQX8TC16UqprSwj18jals2J1T1qdCafOB6gJhfAmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T08:39:14Z"
    mac: ENC[AES256_GCM,data:aLI2UCxwU5s2y8ezS3VKJC9hbbFcp7ibH9sDR0WDouUicpFcIFxzd8Hs3E079ZV3p9cf1RC386NELiPt7LG3t/KpDBz2uQrb5/28L2UJ17jwVynaN+NVQ4Uv8A/IC0bUORT2G6yAUc23PrpBzwptc8qrS5D64a/GRum8huTUJ6w=,iv:CaJyum+71E3olvZHWWgAiCisKi1iwcSTop8dmhnieKg=,tag:JMF5mKbrTzrIfobenOYD+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
