apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - weave-gitops
  - metallb-kustomization.yaml
  - metallb-config-kustomization.yaml
  - traefik
  - nginx
  - cert-manager-kustomization.yaml
  - cert-manager-issuer-kustomization.yaml
  - ddns-updater/dns-secret
  - ddns-updater/flux
  - cloudflare
  - nfs-csi
